import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "@/components/Footer";
import Head from "next/head";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <Head>
        <link
          rel='icon'
          type='image/png'
          href='/favicon-96x96.png'
          sizes='96x96'
        />
        <link rel='icon' type='image/svg+xml' href='/favicon.svg' />
        <link rel='shortcut icon' href='/favicon.ico' />
        <link
          rel='apple-touch-icon'
          sizes='180x180'
          href='/apple-touch-icon.png'
        />
        <link rel='manifest' href='/site.webmanifest' />
      </Head>
      <body className=' font-roboto'>
        <div className='relative min-h-screen bg-[#ebebeb] overflow-hidden'>
          {/* Blurred Circle Background */}
          <div
            className='absolute -top-[800px] md:-top-[400px] -right-[700px] md:right-0 w-[1241px] h-[1241px] bg-circle rounded-full blur-3xl'
            style={{ transform: "translateX(30%)" }}
          ></div>
          <Navbar />
          <main>{children}</main>
        </div>
        <Footer />
        <div id="modal-root"></div>
      </body>
    </html>
  );
}
